import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import GridLayout from 'react-grid-layout';
import React from 'react'
import MyColorPicker from '../components/MyColorPicker'
import '../node_modules/react-grid-layout/css/styles.css'
import '../node_modules/react-resizable/css/styles.css'


// class MyFirstGrid extends React.Component {
//   render() {
//     return (
//       <GridLayout className="layout" cols={12} rowHeight={30} width={1200}>
//         <div key="a" data-grid={{x: 0, y: 0, w: 1, h: 2, static: true}}>a</div>
//         <div key="b" data-grid={{x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4}}>b</div>
//         <div key="c" data-grid={{x: 4, y: 0, w: 1, h: 2}}>c</div>
//       </GridLayout>
//     )
//   }
// }

class MyFirstGrid extends React.Component {
  render() {
    // layout is an array of objects, see the demo for more complete usage
    const layout = [
      {i: 'a', x: 0, y: 0, w: 1, h: 2, static: true},
      {i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
      {i: 'c', x: 4, y: 0, w: 1, h: 2}
    ];
    return (
      <GridLayout className="layout" layout={layout} cols={12} rowHeight={30} width={1200}>
        <div key="a" className={styles.layoutBox}>a</div>
        <div key="b" className={styles.layoutBox}>b</div>
        <div key="c" className={styles.layoutBox}>c</div>
      </GridLayout>
    )
  }
}

function sendColor(color) {
  const requestOptions = {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ color: 'blue' })
  };
  fetch(`http://192.168.1.32:5000/${color}`, requestOptions)
  .then(response=>{
    console.log(response.ok);
    response.text();
  })
  .catch(
      console.log("this is okay")
  );
}


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Maya
        </h1>
        <div className={styles.container}>
          <MyColorPicker />
          {/* <MyFirstGrid></MyFirstGrid> */}
        </div>
      </main>
    </div>
  )
}
